feshar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'polls' # So we can use it like: {% url 'mymodule:user_register' %} on our template.
urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout.', views.logout_view, name='logout'),
    path('home/', views.home_view, name='home'),
    path('users/', views.users_view, name='users'),
    path('ngp/', views.ngp_student_view, name='ngp'),
    path('gp/', views.gp_student_view, name='gp'),
    path('cant/', views.cant_view, name='cant'),
    path('get_national_id/', views.get_national_id_view, name='get_national_id'),
    path('get_payment_id/', views.get_payment_id_view, name='get_payment_id'),
    path('table_shift/', views.table_shift_view, name='table_shift'),
    path('table_user/', views.table_user_view , name='table_user'),


    #url('take/', views.take_view ,name='take'),
    path('delete/<int:usr_pk>/', views.delete_view ,name='delete'),
    path('user/<int:polluser_pk>/', views.user_view, name='user'),
    path('section/<int:section_pk>/', views.section_view, name='section'),

    path('change_usr_present/<int:usr_pk>/<int:new_state>/', views.change_present_view, name='change_usr_present'),
    path('sections/', views.sections_view, name='sections'),

    path('delete_extra_work/<int:extra_work_pk>/<int:polluser_pk>/', views.delete_extra_work ,name='delete_extra_work'),

    path('staff/<int:polluser_pk>/<int:new_state>', views.staff_veiw, name='staff_state'),

    path('', views.register_view, name='base'),
]

site3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

polls/forms.py
from django import forms

class RegisterForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    phone_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
    student_number = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
    national_id = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
    can_presure = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'form-control'}), required=0, )

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

class NationalIdForm(forms.Form):
    national_id = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))

class PaymentIdForm(forms.Form):
    payment_id = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))

class ExtraWorkForm(forms.Form):
    info = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    hour = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}))

polls/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from .forms import RegisterForm, LoginForm, NationalIdForm, ExtraWorkForm, PaymentIdForm
from django.contrib.auth import  login, logout
from .models import PollUser,Section,USR,entry_year_show, ExtraWork
from django.urls import reverse

from redis import Redis
redis = Redis.from_url('redis://localhost:6379/1')
from pottery import Redlock
import jdatetime

def register_view(request):

    template = 'polls/register.html'
    if(request.user.is_authenticated):
        return HttpResponseRedirect(reverse('polls:home'))
    else:
        if request.method == 'POST':

            form = RegisterForm(request.POST)
            if form.is_valid():
                if User.objects.filter(username=form.cleaned_data['student_number']).exists():
                    return render(request, template, {
                        'form': form,
                        'error_message': 'شما قبلا ثبت نام کرده اید'
                    })
                else:
                    # Create the user:
                    user = User.objects.create_user(
                        username = form.cleaned_data['student_number'],
                        password = form.cleaned_data['phone_number'],
                    )
                    user.save()
                    polluser = PollUser(user = user)
                    polluser.first_name = form.cleaned_data['first_name']
                    polluser.last_name = form.cleaned_data['last_name']
                    polluser.phone_number = form.cleaned_data['phone_number']
                    polluser.national_id = form.cleaned_data['national_id']

                    polluser.entry_year = int(request.POST['entry_year'])
                    polluser.entry_year -= 1

                    polluser.student_number = form.cleaned_data['student_number']
                    polluser.can_presure = form.cleaned_data['can_presure']
                    polluser.sex = request.POST['sex']
                    polluser.save()

                    login(request, user)

                    return HttpResponseRedirect(reverse('polls:home'))
        else:
            form = RegisterForm()

        valid_entry = [entry_year_show(x) for x in range(14)]
        return render(request, template, {'form': form, 'valid_entry':valid_entry})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:register'))


def login_view(request):
    template = 'polls/login.html'
    if request.user.is_authenticated :
        return HttpResponseRedirect(reverse('polls:home'))

    else:
        form = LoginForm(request.POST)

        if request.method == 'POST':
            if form.is_valid():
                if User.objects.filter(username=form.cleaned_data['username']).exists():
                    user = User.objects.get(username=form.cleaned_data['username'])
                    if user.check_password(form.cleaned_data['password']):
                        login(request, user)
                        return HttpResponseRedirect(reverse('polls:home'))

                return render(request, template, {
                    'form': form,
                    'error_message': 'شماره دانشجویی یا رمز عبور اشتباه می باشد'
                })

        else:
            form = LoginForm()
        return render(request, template, {'form': form})

def home_view(request):
    template = 'polls/home.html'
    if request.user.is_authenticated :
        polluser = PollUser.objects.get(user=request.user)
        if(polluser.national_id == "0"):#when user got no national_id
            return HttpResponseRedirect(reverse('polls:get_national_id'))
        if(not polluser.payment_id_valid()):
            return HttpResponseRedirect(reverse('polls:get_payment_id'))
        error_message = ""

        if request.method == 'POST':
            section = Section.objects.get(pk=request.POST['section_pk'])

            reserve_lock = Redlock(key=f"res_{section.pk}", masters={redis}, auto_release_time=60*1000)
            reserve_lock.acquire()

            usrs = section.usr_set.all()
            if len(usrs) >= 3:
                error_message = "این شیفت در این تاریخ و ایستگاه پر شده است"
            elif len(usrs)==2 and usrs[0].polluser.sex==usrs[1].polluser.sex==polluser.sex==0:
                error_message = "ا توجه به طرح تطبیق امکان حضور سه پسر در یک ایستگاه وجود ندارد!!!"
            else:
                # not supported for current jdatetime
                #if USR.objects.filter(section__end__mt=section.start, section__start__lt=section.end, polluser=polluser).exists():
                if [usr for usr in USR.objects.filter(polluser=polluser) if (usr.section.start<section.end and usr.section.end>section.start)]:
                    error_message = "شما قبلا در این روز و تاریخ شیفتی رزرو کرده اید"
                else:
                    #todo
                    if section.available_from <= jdatetime.datetime.now():
                        USR.objects.create(polluser=polluser, section=section)
                        error_message = "رزرو شد"
                    else:
                        error_message = "هم اکنون امکان رزرو شیفت وجود ندارد"

            reserve_lock.release()
        #  day.section_set.order_by('index', 'station')
        sections = [section for section in Section.objects.filter(available_from__lt=jdatetime.datetime.now()) if section.usr_set.count()<3]

        user_usr = [usr for usr in USR.objects.filter(polluser__user=request.user).order_by('section__start')]
        return render(request, template, {'sections': sections, 'error_message': error_message, 'user_usr': user_usr, 'polluser':polluser})
    else:
        return HttpResponseRedirect(reverse('polls:register'))

def delete_view(request, usr_pk):
    if request.user.is_authenticated :
        try:
            usr = USR.objects.get(pk=usr_pk)
            try:
                if usr.polluser.user == request.user:
                    if usr.section.deletable_until > jdatetime.datetime.now():
                        usr.delete()
                return HttpResponseRedirect(reverse('polls:home'))
            except:
                return HttpResponseRedirect(reverse('polls:home'))
        except:
            return HttpResponseRedirect('polls:home')
    else:
        return HttpResponseRedirect(reverse('polls:register'))


def sections_view(request):
    if request.user.is_staff or request.user.is_superuser:
        template = 'polls/sections.html'
        error_message=""
        needed_dates=[  ('start','زمان شروع'),
                        ('end','زمان پایان'),
                        ('available_from','قابل رزرو از'),
                        ('deletable_until','قابل لغو تا')]
        if request.method == 'POST':
            dates=dict()
            header = request.POST.get('header')
            detail = request.POST.get('detail')

            if not header:
                error_message = "عنوان خالی است"
            elif not detail:
                error_message = "جزییات خالی است"
            else:
                try:
                    for t,name in needed_dates:
                        dates[t] = jdatetime.datetime(
                                        int(request.POST.get(f"{t}__year")),
                                        int(request.POST.get(f"{t}__month")),
                                        int(request.POST.get(f"{t}__day")),
                                        int(request.POST.get(f"{t}__hour")),
                                        int(request.POST.get(f"{t}__minute")),)
                except:
                    error_message= "ورودی نامناسب"
                # available < deletable <= start < end
                if not error_message:
                    if dates['available_from'] >= dates['deletable_until']:
                        error_message= "آخربن زمان مجاز حذف باید پس از زمان مجاز ثبت رزور باشد"
                    elif dates['deletable_until'] > dates['start']:
                        error_message= "زمان قابل رزرو شدن باید پس قبل از زمان شروع باشد"
                    elif dates['start'] >= dates['end']:
                        error_message= "زمان پایان باید پس از زمان شروع باشد"
                    else:
                        Section.objects.create(header=header, detail=detail,
                            start=dates['start'], end=dates['end'],
                            available_from=dates['available_from'],
                            deletable_until=dates['deletable_until'])

        ### cubing by date
        dic={}
        dates=[]
        for section in Section.objects.all():
            date = section.start.date()
            if date not in dic:
                dates.append(date)
                dic[date] = [section]
            if date in dic:
                dic[date].append(section)

        sections = [dic[date] for date in dates]
        ###  end of cubing by date
        current_datetime = jdatetime.datetime.now()
        months= ['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند']
        return render(request, template, {'sections':sections, 'months':months, 'current_datetime':current_datetime, 'needed_dates':needed_dates, 'error_message':error_message})
    else:
        return HttpResponseRedirect(reverse('polls:home'))

def user_view(request ,polluser_pk):
    if request.user.is_staff or request.user.is_superuser:
        template = 'polls/user.html'
        try:
            polluser = PollUser.objects.get(pk = polluser_pk)
            if request.method == 'POST':
                form = ExtraWorkForm(request.POST)
                if form.is_valid():
                    ew = ExtraWork(polluser=polluser, hour=form.cleaned_data['hour'] ,info=form.cleaned_data['info'])
                    ew.save()

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>غربال‌گری فشار خون</title>

  <style media="screen">
  @media screen and (max-width: 768px) {
    .logout-submit{
      float:left;
      margin: 14px 6px 0 0;
    }
  }
    .logout-submit{
      float:left;
      margin: 14px 13px 0 0;
    }
  </style>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">


</head>
<body class="override">
    <nav class="navbar navbar-inverse" role="navigation" >
        <div class="container">
          {% block data %}{% endblock %}
          {% if request.user.is_staff or request.user.is_superuser %}
          <a href="{% url 'polls:users' %}" class="logout-submit">کاربران</a>
          <a href="{% url 'polls:sections' %}" class="logout-submit">شیفت ها</a>
          <a href="{% url 'polls:gp' %}" class="logout-submit">پزشکی</a>
          <a href="{% url 'polls:ngp' %}" class="logout-submit">غیر‌پزشکی</a>
          <a href="{% url 'polls:cant' %}" class="logout-submit">نیازمند آموزش</a>
          <a href="{% url 'polls:table_user' %}" class="logout-submit">اطلاعات چاپی افراد</a>
          <a href="{% url 'polls:table_shift' %}" class="logout-submit">اطلاعات چاپی شیفت ها</a>
          {% endif %}
            <div class="navbar-header">
                <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button> -->
                <a class="navbar-brand" href="{% url 'polls:home' %}">غربال‌گری فشار خون</a>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

polls/templates/polls/cant.html
{% extends "polls/base.html" %}
{% block data %}
<a href="{% url 'polls:logout' %}"class="logout-submit">خروج</a>
{% endblock %}
{% block content %}
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading" >افراد نیازمند آموزش برای گرفتن فشار که شیفت دارند</div>
        <div class="panel-body">
          <div class="col-md-12 col-md-offset-0">
            <table class="table">
              <tbody>
                <tr>
                  <th>نام</th>
                  <th>شماره دانشجویی</th>
                  <th>شماره تماس</th>
                </tr>
                {% for polluser in pollusers %}
                {% if polluser.can_presure %}
                {% else %}
                {% if polluser.usr_set.count %}
                <tr>
                  <td><a href="{% url 'polls:user' polluser.pk %}">{{ polluser.full_name }}</a></td>
                  <td>{{ polluser.f_student_number }}</td>
                  <td>{{ polluser.f_phone_number }}</td>
                </tr>
                {% endif %}
                {% endif %}
                {% endfor %}
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/gpstudent.html
{% extends "polls/base.html" %}
{% block data %}
<a href="{% url 'polls:logout' %}"class="logout-submit">خروج</a>
{% endblock %}
{% block content %}
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading" >دانشجویان پزشکی که شیفت دارند</div>
        <div class="panel-body">
          <div class="col-md-12 col-md-offset-0">
            <table class="table">
              <tbody>
                <tr>
                  <th>نام</th>
                  <th>شماره دانشجویی</th>
                  <th>شماره تماس</th>
                </tr>
                {% for polluser in pollusers %}
                {% if polluser.is_gp_student %}
                {% if polluser.usr_set.count %}
                <tr>
                  <td><a href="{% url 'polls:user' polluser.pk %}">{{ polluser.full_name }}</a></td>
                  <td>{{ polluser.f_student_number }}</td>
                  <td>{{ polluser.f_phone_number }}</td>
                </tr>
                {% endif %}
                {% endif %}
                {% endfor %}
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/home.html
{% extends "polls/base.html" %}
{% block data %}
<a href="{% url 'polls:logout' %}"class="logout-submit">خروج</a>
{% endblock %}
{% block content %}
<div class="container">

<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">اطلاعات شما</div>
      <div class="panel-body">
        <div class="col-md-12 col-md-offset-0">
          <table class="table table-striped">
            <tbody>
              <tr>
                <td>نام</td>
                <td>{{ polluser.first_name }}</td>
              </tr>
              <tr>
                <td>نام خانوادگی</td>
                <td>{{ polluser.last_name }}</td>
              </tr>
              <tr>
                <td>کد ملی</td>
                <td><a href="{% url 'polls:get_national_id' %}" style="color:black">{{ polluser.f_national_id }}</a></td>
              </tr>
              <tr>
                <td>شماره دانشجویی</td>
                <td>{{ polluser.f_student_number }}</td>
              </tr>
              <tr>
                <td>ورودی</td>
                <td>{{ polluser.show_year }}</td>
              </tr>
              <tr>
                <td>شماره تلفن</td>
                <td>{{ polluser.f_phone_number }}</td>
              </tr>
              <tr>
                <td>شماره حساب</td>
                <td><a href="{% url 'polls:get_payment_id' %}" style="color:black">{{ polluser.payment_id }}</a></td>
              </tr>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>



  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">شیفت های رزرو شده توسط شما</div>
        <div class="panel-body">
          <div class="col-md-12 col-md-offset-0">
          {% for usr in user_usr %}
          <form action="{% url 'polls:delete' usr.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="لغو" class="btn btn-danger btn-xs" name="iii">
            <label {%if usr.section.anti_tatbiq%} {%endif%}>{{ usr.section.header_with_date }}</label>
          </form>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>


    <form action="{% url 'polls:home' %}" method="post">
        {% csrf_token %}
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">شیفت های موجود</div>
                <div class="panel-body">
                    {% if error_message %}
                        <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                    {% endif %}
                    <div class="form-group">
                      <label for="exampleFormControlSelect1">لطفا از میان شیفت های موجود شیفت های مورد نظر خود را انتخاب کنید</label>
                      <select class="form-control" id="exampleFormControlSelect1" name="section_pk">
                          {% for section in sections %}
                            <option value= {{section.pk}} > {{section.header_with_date}} </option>
                          {% endfor %}
                      </select>
                    </div>
                    <div class="col-md-6 col-md-offset-5 ">
                        <input type="submit" value="رزرو" class="btn btn-success ">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

polls/templates/polls/section.html
{% extends "polls/base.html" %}
{% block data %}
<a href="{% url 'polls:logout' %}"class="logout-submit">خروج</a>
{% endblock %}
{% block content %}
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading" {% if section.anti_tatbiq %}style="color:red"{% endif %}>{{ section.header_with_date }}</div>
      <div class="panel-body">
        <div class="col-md-12 col-md-offset-0">
          {% for usr in section.usr_set.all %}
            {% if usr.is_present %}
            <form action="{% url 'polls:change_usr_present' usr.pk 0 %}" method="post">
            <input type="submit" value="حاضر" class="btn btn-success btn-xs" name="iii">
            {% else %}
            <form action="{% url 'polls:change_usr_present' usr.pk 1 %}" method="post">
            <input type="submit" value="غائب" class="btn btn-danger  btn-xs" name="iii">
            {% endif %}
            {% csrf_token %}
            <a href="{% url 'polls:user' usr.polluser.pk %}">{{ usr.polluser.full_name }}</a>
          </form>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/sections.html
{% extends "polls/base.html" %}
{% block data %}
<a href="{% url 'polls:logout' %}"class="logout-submit">خروج</a>
{% endblock %}
{% block content %}
<div class="container">
    <form action="{% url 'polls:sections' %}" method="post">
        {% csrf_token %}
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">ثبت شیفت جدید</div>
                <div class="panel-body">
                    {% if error_message %}
                        <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                    {% endif %}

                    <div class="form-group clearfix">
                        <label class="col-md-4 control-label text-right">عنوان</label>
                        <div class="col-md-6">
                            <input type="text" name="header">
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label class="col-md-4 control-label text-right">جزییات</label>
                        <div class="col-md-6">
                            <input type="bigtext" name="detail">
                        </div>
                    </div>
                    {% for date, name in needed_dates %}
                    <div class="form-group clearfix">
                      <label class="col control-label text-right">{{name}}</label>
                      <div class="col">
                      <input type="Number" name="{{date}}__day" value="{{current_datetime.day}}">
                      <select name="{{date}}__month" >
                        {% for month in months%}
                        <option value={{forloop.counter}} {% if forloop.counter == current_datetime.month %} {{ 'selected="selected"' }}{% endif %} >{{ month }}</option>
                        {% endfor %}
                      </select>
                      <input type="Number" name="{{date}}__year" value="{{current_datetime.year}}">
                    </div>
                    <div class="col">
                      <input type="number" name="{{date}}__minute" value="{{current_datetime.minute}}">
                      <input type="number" name="{{date}}__hour" value="{{current_datetime.hour}}">
                    </div>
                      <br>
                    </div>
                    {% endfor %}
                    <div class="form-group clearfix">
                        <div class="col-md-6 col-md-offset-4">
                            <input type="submit" value="ثبت شیفت جدید" class="btn btn-success">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% for sec_list in sections %}
{% for section in sec_list %}
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading" ><a href="{% url 'polls:section' section.pk %}"{% if section.anti_tatbiq %}style="color:red"{% endif %}>{{ section.header_with_date }}</a></div>
        <div class="panel-body">
          <div class="col-md-12 col-md-offset-0">
            <table class="table">
              <tbody>
                <tr>
                  {% for usr in section.usr_set.all %}
                  <td><a href="{% url 'polls:user' usr.polluser.pk %}">{{ usr.polluser.full_name }}</a></td>
                  {% endfor %}
                </tr>
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endfor %}

{% endblock %}

polls/templates/polls/user.html
{% extends "polls/base.html" %}
{% block data %}
<a href="{% url 'polls:logout' %}"class="logout-submit">خروج</a>
{% endblock %}
{% block content %}
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">اطلاعات ‌ ‌ {{ polluser.first_name }}-{{ polluser.last_name }}</div>
        <div class="panel-body">
          {% if error_message %}
            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
          {% endif %}
          <div class="col-md-12 col-md-offset-0">
            <table class="table table-striped">
              <tbody>
                <tr>
                  <td>نام</td>
                  <td>{{polluser.first_name}}</td>
                </tr>
                <tr>
                  <td>نام خانوادگی</td>
                  <td>{{polluser.last_name}}</td>
                </tr>
                <tr>
                  <td>کد ملی</td>
                  <td>{{polluser.f_national_id}}</td>
                </tr>
                <tr>
                  <td>شماره دانشجویی</td>
                  <td>{{polluser.f_student_number}}</td>
                </tr>
                <tr>
                  <td>ورودی</td>
                  <td>{{polluser.show_year}}</td>
                </tr>
                <tr>
                  <td>شماره تلفن</td>
                  <td>{{polluser.f_phone_number}}</td>
                </tr>
                <tr>
                  <td>شماره حساب</td>
                  <td>{{ polluser.payment_id }}</td>
                </tr>
                <tr>
                  <td>آیا به نحوه گرفتن فشار خون آگاه است</td>
                  <td>{{polluser.can_str}}</td>
                </tr>
                <tr>
                  <td>وضعیت کاربر</td>
                  <td>{% if polluser.user.is_staff %}{{ 'ناظر' }}{% else %}{ 'کاربر عادی' }{% endif %}</td>
                </tr>
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">تغییر سطح دسترسی</div>
        <div class="panel-body">
          <div class="col-md-12 col-md-offset-0">

            <div class="col-md-6 col-md-offset-4 btn btn-success">
              <a href="{% url 'polls:staff_state' polluser.pk 1 %}">ارتقاع به ناظر</a>
            </div>

            <div class="col-md-6 col-md-offset-4 btn btn-danger">
              <a href="{% url 'polls:staff_state' polluser.pk 0 %}">تبدیل به کاربر عادی</a>
            </div>

          </div>
        </div>
      </div>
    </div>
</div>


<div class="container">
  <form action="{% url 'polls:user' polluser.pk %}" method="post">
    {% csrf_token %}
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">فرم اضافه کردن اضافه کاری</div>
        <div class="panel-body">
          <div class="col-md-12 col-md-offset-0">
            <div class="form-group clearfix">
              <label class="col-md-4 control-label text-right">ساعت</label>
              <div class="col-md-6">
                  {{ form.hour }}
              </div>
            </div>

            <div class="form-group clearfix">
              <label class="col-md-4 control-label text-right">اطلاعات تا ۱۰۰ کاراکتر</label>
              <div class="col-md-6">
                  {{ form.info }}
              </div>
            </div>

            <div class="col-md-6 col-md-offset-4">
                <input type="submit" value="ثبت" class="btn btn-success">
            </div>

          </div>
        </div>
      </div>
    </div>
  </form>
</div>

<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">شیفت های رزرو شده</div>
        <div class="panel-body">
          <div class="col-md-12 col-md-offset-0">
            <ul>
              {% for usr in polluser.usr_set.all %}
                <li><a href="{% url 'polls:section' usr.section.pk %}">{{ usr.section.header_with_date }}</a></li>
              {% endfor %}
            </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">اضافه کاری ها</div>
        <div class="panel-body">
          <div class="col-md-12 col-md-offset-0">
            <ul>
              {% for ew in polluser.extrawork_set.all %}
                <ll><form class="" action="{% url 'polls:delete_extra_work' ew.pk polluser.pk %}" method="post">
                  {% csrf_token %}
                  <div>
                      <input type="submit" value="X" class="btn btn-danger btn-sm">
                  </div>
                </form>اطلاعات: {{ ew.info }}<br>ساعت: {{ ew.f_hour }}</ll>
              {% endfor %}
            </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}